elementary-robotics/atom

- .circleci/config.yml
- README.md
- docker-compose.yml
Project name wasn't being specified. Addresses bug from #145
> README: fix bug in docs

- doc/source/includes/walkthrough.md
> walkthrough.md:Corrected Msgpack Instruction

- .dockerignore
> Remove .circleci from dockerignore

- doc/source/includes/sdk-graphics.md
> Clarify X11 graphics with and without GPU in docs

- languages/python/atom/element.py
- languages/python/tests/test_atom.py
> Handle None passed as value in raw_data dict

- doc/source/includes/sdk-specification.md
- languages/python/atom/element.py
- languages/python/tests/test_atom.py
Returns a list now rather than a dictionary
> Change return type of reference_get()

- .circleci/atom.yml
- .circleci/config.yml
- docker-compose-circle.yml
When a GitHub tag is created, a master build will be triggered. The docker image will be pushed with the following tags:
- `master-<circle build number>`
- `latest`
- `<GitHub tag>`
> Trigger CircleCI builds on GitHub tags (#237)

- .circleci/config.yml
Update image tag used in docs heroku deploy.
> Issue #240 -- Fix docs heroku deploy

- .circleci/atom.yml
- .circleci/config.yml
A bug in building on tags was discovered in testing on this repo. This PR includes the fix and example in orb.
> Fix bug in building on tags (#237)

- .circleci/README.md
Added release notes for v0.0.2, v0.0.3 and v0.0.4.
Resolves #243
> Issue #243 - Add Circle orb release notes to README

- .circleci/README.md
- .circleci/atom.yml
- .circleci/config.yml
- .dockerignore
- Dockerfile-atom
- Dockerfile-nucleus
- languages/python/requirements.txt
- Remove `--no-cache` option from `docker-compose build` command
- Increase build machine sizes to large
Published dev orb ` elementaryrobotics/atom@dev:251`
Resolves #251
> Issue #251 - Update build for new plan

- .circleci/config.yml
- languages/python/atom/element.py
- utilities/atom-cli/atom-cli.py
Resolves #250. 
Possible similar issue noted at https://github.com/elementary-robotics/atom/blob/c707e6e6da60dfe63a906cdec42e3825c7a4f9d8/utilities/atom-cli/atom-cli.py#L244
> Issue #250 - Rely on element for deserialization rather than CLI

- Dockerfile-atom
> Add .circleci to atom image for docs build (#258)

- .circleci/README.md
- .circleci/config.yml
> Issue #265 - Fix docs tag deploy; update orb docs formatting

- languages/python/atom/element.py
> Add force_serialization param to docstrings (#268)

- .circleci/README.md
- .circleci/atom.yml
- .circleci/config.yml
- Dockerfile-atom
Resolves #276 
Orb needs promotion to prod.
> Issue #276 - Add flake8 orb command

- .circleci/config.yml
Need to add logic converting "" -> "latest"
> .circleci: work on getting master to deploy

- .circleci/config.yml
Another attempt at fixing master tag deploys
> .circleci: fix master tagging

- .circleci/README.md
- .circleci/atom.yml
> .circleci: add in use_git_lfs for tests

- metrics/dashboards/create_dashboards.py
> create_dashboards: add in user dashboards

- docker-compose-dev.yml
- languages/python/atom/element.py
> Improve sorted_set_add signature

- docker-compose-dev.yml
- languages/python/atom/config.py
- languages/python/setup.py
- languages/python/setup_local.py
> bump atom to version 2.6.1

- languages/python/atom/element.py
> clear handlers when creating logger

- languages/python/atom/messages.py
> Add "id" and "meta" keys

- .circleci/config.yml
- Hadn't updated for new tagging system
> .circleci: fix docs deploy

- languages/python/atom/messages.py
Makes it much easier to print out a response
> add __str__ and __repr__ to Response

- languages/python/atom/config.py
- languages/python/atom/element.py
Should cut our RTS memory usage by 30-50%
> atom: decrease chunk size for RTS from 4k to 1k
