elementary-robotics/atom

utilities/atom-cli/atom-cli.py
This assures that every atom-cli instance has a unique element name, even when multiple instances are launched on the same device/container.
=> Append UUID4 hex string to atom-cli element name

.gitignore, languages/python/atom/element.py, languages/python/tests/test_atom.py
Discovered a bug in the Element class, where we get redis client crashes if we try to publish at >5-10 hz to a stream on one thread, while running the command_loop and handling incoming commands on another thread. This is a paradigm we rely on in some of our other element repos, (for example: https://github.com/elementary-robotics/element-instance-segmentation/blob/master/run.py), but up till now we haven't been running them fast enough to hit this consistently. After some digging, I traced the problem to the use of a shared redis `_pipeline` inside the Element class. From the thread safety section of the pyredis docs: `It is not safe to pass PubSub or Pipeline objects between threads`: (https://github.com/andymccurdy/redis-py/blob/master/README.rst#thread-safety)
This PR addresses the …
=> Fix for concurrency bug in python library, and corresponding test

languages/python/atom/config.py, languages/python/atom/element.py, languages/python/tests/test_atom.py, utilities/atom-cli/atom-cli.py
Support for #62 
Implements checking of available commands through atom-cli with the same front facing interface of "list streams". In atom-cli, "list commands" displays all available commands for all elements, while "list commands <element>" displays available commands for a single element. 
Retrieval of an element's commands uses a custom implemented command, similar to health and version checks, to prevent creating additional Redis structures. 
Retrieval of all commands at once is achieved by iterating through all existing Elements, sending a command to each. As a side-effect, for any Elements that do not have an active command loop, a failed to receive acknowledge is logged, as that Element will not be responding to commands. For the purpose of atom-cli, this is bypassed by not …
=> Python support for retrieving available commands of elements in atom-cli

doc/source/includes/sdk-introduction.md
Specification link was previously redirecting to
the wrong part of the page.
=> sdk introduction: fix broken specification link

redis.conf
Temporary fix to issues with command/response streams being too
long and wasting a bunch of memory -- should be able to revert
and/or downsize once that fix is in across the SDK.
=> redis.conf: increase maxmemory to 2gb

doc/source/includes/sdk-specification.md, docker-compose.yml, languages/python/atom/element.py, languages/python/atom/messages.py, languages/python/tests/test_atom.py
This will allow us to msgpack main commands but still
send additional data (such as an image) over the raw data
side-channel and it will be passed as a kwarg to the
handler.
Addition of new side-channel causes no code changes to
existing elements
=> python: add side-channel for raw data

languages/python/atom/element.py, languages/python/tests/test_atom.py
Previously when serialization was true for entry_write, we would
overwrite the provided field_data_map values with serialized values
Now we create a separate dictionary for the serialized data
Tests added to ensure the integrity of the original data as well
=> Fix bug where entry data was overwritten on serialization

doc/Dockerfile
- Specify version of bundler to install per [bundler blogpost](https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html)
- Install gem through OS package manager to avoid installing deprecated ruby per [gem issue](https://github.com/rubygems/rubygems/issues/3068)
Resolves #232
=> #232 - Fix nightly docs build

.circleci/atom.yml
In testing this change for https://github.com/elementary-robotics/element-barcode/issues/10 a bug in the new orb's deploy jobs was discovered where the workspace was not attached before loading a stored image. The fix has been included in this PR.
=> Issue #239 -- Add Git-LFS install command to orb

.circleci/atom.yml
Parameterized the `docker push` command's `no_output_timeout` parameter in atom orb, exposed through both the commands and jobs used to deploy images. This should be tested with dev orb ` elementaryrobotics/atom@dev:236` in `element-defect-detection` before publishing to prod and merging.
Resolves #236
=> Issue #236 - Parameterize docker push "no output timeout"

.circleci/README.md, .circleci/atom.yml, .circleci/config.yml
Resolves #248 
Published dev orb at `elementaryrobotics/atom@dev:243` which should be promoted to prod
=> Remove git hash from master tags (#248)

.circleci/README.md, .dockerignore
Remove `.circleci` from `.dockerignore`; change orb release notes formatting.
Resolves #258
=> Issue #258 - Fix docs build and formatting

Dockerfile-atom
Edit graphics app shebang to explicitly use python2 - required now since we are defaulting to python3.
=> Run graphics app with python2

doc/Gemfile.lock
This reverts commit 69706ecc3d7116f6a0d6aa4e8034466fb83e98a4.
=> Revert "Bump rack from 2.0.5 to 2.2.2 in /doc"

.circleci/atom.yml, .circleci/config.yml, Dockerfile-atom, README.md
See #275 
An initial build on this PR failed because an `apt-get update` was cached, but the version of a library it tried to download was no longer available. I created a `LAST_UPDATED` env var within the Dockerfile to use for invalidating the `apt-get update` cache when necessary.
=> Remove latest bump from tagged builds (Issue #275)

.circleci/README.md, .circleci/atom.yml, .circleci/config.yml, Dockerfile-atom
Update to PR #284 addressing Issue #276.
The flake8 format check has been changed from a command to a job, which is run in the `alpine/flake8` docker image. The python version to use is now a parameter which also determines which image tag to use. The available image tags corresponding to python versions can be viewed on [dockerhub](https://hub.docker.com/r/alpine/flake8). The default python version/image tag is set to `3.7.0`. See updated docs included in this PR for instructions on use.
This orb will need promotion to production version `0.0.9`.
=> Update flake8 check to run as job in docker image

.circleci/Dockerfile-flake8, .circleci/README.md, .circleci/atom.yml, .circleci/config.yml
Install git and openssh in flake8 container.
Atom orb needs updating to prod before merge.
=> Fix failing flake8 step on tag builds

.circleci/atom.yml, .circleci/config.yml
- bump orb in order to have a deploy command without
auto-adding -variant-platform
- Use above orb to fix base master deploy
- Add base tag deploy
- Fix docs push to heroku
=> atom tagging: improve

.circleci/README.md, .circleci/atom.yml
- Were using source image tag for target deploy. This
breaks when you use different repos which is a rare, but
real use case
=> atom.yml: fix bug in deploy

.circleci/config.yml, docker-compose-dev.yml, languages/python/atom/element.py, languages/python/tests/test_atom.py
This argument will enforce that after we have established
a connection with the remote redis and we have sent it a command
we will wait for no longer than this number of milliseconds for data.
NOTE: This timeout is above and supersedes any timeouts set by
blocking redis calls, i.e. if you're using a N millisecond blocking
redis call you MUST instantiate your element with a data_timeout_ms
slightly greater than N. If data_timeout_ms is less than N the socket
will time out during the valid redis blocking window. This is by
design and desirable as we want to use this data_timeout_ms on the
linux/TCP socket level s.t. we can detect failed network connections.
The default timeout is 5s as there are not many blocking calls >5s
in known codebases. It's also generally recommended to implement …
=> Python element: add data_timeout_ms constructor arg

languages/python/atom/element.py
When multiple instances of an element utilize the element logger, a new rotating file handler is added to the logger each time. This was causing duplicate log messages to be outputted to the ATOM_LOG_DIR.
=> Deduplicate log messages

languages/python/atom/element.py
- Existing code depends on some longer-running blocking calls.
- This timeout was added to guard against faulty network
connections, we don't have this class of issues when connecting
via unix socket
=> element: don't use data timeout for unix socket connections

.circleci/README.md, .circleci/atom.yml
Adds in automatic build labeling to all Atom orb users (on orb upgrade). See README for info
=> atom orb: add build labels

.circleci/README.md, .circleci/atom.yml, .circleci/config.yml
- Upgrade docker to 20.10.2 to fix missing file bug
- launch/inspect the build engine before running build to
fix intermittent failure bug.
=> atom: build improvements

.circleci/README.md, .circleci/atom.yml, .circleci/config.yml
Atom ARM builds (for shipped atom containers, not base builds at the moment) now build using CircleCI's new ARM resources. This drastically improves build time and reduces cost by no longer needing to run everything for ARM in simulation through QEMU in the `buildx` docker engine.
This does make a slight breaking change to the orb, so the orb is now bumped to `0.2.0`. Upgrade instructions for users are fairly straightforward, and the build config required for anyone using the orb is slightly wordier/more verbose. See circleci README in this PR for more info.
Rebasing #404 atop this should fix the unit tests failing at the moment due to being CPU constrained on ARM builds.
=> Orb Support for ARM executors

metrics/README.md
Add docs describing the `save_dashboard.py` script and instructions for how to get the dashboard uid.
=> Dashboard docs update

.circleci/README.md, .circleci/atom.yml, .circleci/config.yml, .circleci/templates/config_basic.yml, .circleci/templates/config_prod_and_test.yml
- Use the buildkit container driver to decouple buildkit version
from the installed version of Docker on the CircleCI images.
- Use/upgrade to buildkit v0.8.3 to attempt to fix missing layer
bug/issue
=> atom orb: upgade buildkit to v0.8.3

doc/source/includes/walkthrough.md, languages/python/atom/element.py, utilities/atom-cli/atom-cli.py
This commit fixes the atom-cli  records command for the cmdres subcommand and removes the records log subcommand.
=> Atom-cli: Fixed the atom-cli records command.

doc/source/includes/sdk-specification.md, languages/python/atom/element.py, languages/python/tests/test_atom.py
Adds new parameter to `entry_write` which allows for overriding the stream's element name. Defaults to the calling element name if unspecified.
=> Add ability to override element name on entry write

languages/python/atom/config.py, languages/python/atom/element.py
- Reduces metrics max retention to 10m to reduce overall memory hit for metrics
- Initializes default timing aggregation to None. This shouldn't have much effect as aggregation was already off by default, but was mainly good cleanup
=> metrics: drop default retention down to 10m

.circleci/config.yml, Dockerfile
Working to remove some non-essential packages and found a few improvements in the build which do so:
1. We were shipping the `test` stage of the Dockerfile instead of the `atom` stage without realizing it due to both images pushing to the same dockerhub tag. This has been amended and the test image now adds `-test` into the tag string and it's been validated we're no longer shipping test dependencies in the release builds. This removed `npm` which removed all of the NPM source/deps.
2. We are building RedisTimeSeries from source. Their build process requires python, and installs a few packages that are build-only and not needed at runtime. The build for this dependency has been moved to a virtualenv so that it no longer impacts the production build environment
=> Ers 617/remove click and through

languages/python/atom/element.py, languages/python/tests/test_atom.py
Closes https://elementary.atlassian.net/browse/ERS-855
- adds `use_procs` arg to `command_loop`, which defaults to true, but can be set to false to use threads for command loop instead of processes
- removes the need to do this kind of stuff, e.g. in integration framework
```py
command_thread = Thread(
target=self.element._command_loop,
args=(
self.element._command_loop_shutdown,
0,
),
daemon=True,
)
```
Dan and I agreed it would be better to go with the multi-element fix to https://elementary.atlassian.net/browse/ERS-851, especially because we want to hotfix this back into 2.3
Still, this is a good feature to add, and once it's verified working we can use this solve for wherever we want a multi-threaded command loop
=> Optionally use threads in command_loop

languages/python/atom/element.py
https://elementary.atlassian.net/browse/ERS-1268
https://elementary.atlassian.net/browse/ERS-1268
=> Client can optionally pass Redis stream id to entry_write

.circleci/config.yml, Dockerfile
ERS-1357 bump base Ubuntu to resolve CVE-2021-3711 and CVE-2021-33910
=> ERS-1357 bump base Ubuntu to resolve CVE-2021-3711 and CVE-2021-33910

Dockerfile
ERS-1357 upgrade packages released since last Ubuntu image
This should also ensure that packages are updated for each new Atom build as opposed to us manually incrementing the Ubuntu base.
- [] Bug fix (fixes an issue)
=> ERS-1357 upgrade packages released since last Ubuntu image

metrics/Dockerfile
ERS-1358 upgrade grafana and grafana-redis-datasource used in metrics
This will upgrade grafana from 7.5.7 to 8.1.3 and will upgrade grafana-redis-datasource plugin from 1.4.0 to 1.5.0 to resolve some identified vulnerabilities.
- [] Application changes have been tested thoroughly
=> ERS-1358 upgrade grafana and grafana-redis-datasource
